app:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/first
      username: dbuser
      password: dbpass
      configuration:
        maximum-pool-size: 30
    second:
          url: jdbc:mysql://localhost:3306/second
          username: dbuser
          password: dbpass
          configuration:
            maximum-pool-size: 30
mybatis:
  type-aliases-package:
  mapper-locations:
